
# Part 1

### 1.
line 9 prints "values added: 20"

### 2.
line 13 prints "final result: 20"
(var result is still accessed within function)

### 3.
line 9 prints "values added: 20"
(result printed in same block)

### 4.
code returns an error because result is accessed when let declaration not in same block

### 5.
code returns an error because result variable is attempted to be reassigned on line 7

### 6.
code returns an error because there is no variable result within that scope
